apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-server
spec:
  selector:
    matchLabels:
      app: html-server
  replicas: 1
  template:
    metadata:
      labels:
        app: html-server
    spec:
      containers:
      - name: html-server
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: html-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: html-server
